#!/usr/bin/env python3
"""
gen_inc.py - generate payload_inc.h / payload_inc.cs from builder artifacts

Reads the demo payload produced by shellcrypt.py from payloads/ and emits a
standalone C include or C# static class that loader templates #include/embed.

Usage:
  python3 tools/gen_inc.py <cipher> <size> [--lang cpp|cs] [--out FILE]
    cipher : aes_cbc | aes_ctr | xor | rc4 | bcrypt | chacha20 | uuid
    size   : 4 | 300

Artifacts consumed (see payloads/):
  <cipher>_<size>b.bin   - raw encrypted blob (all ciphers except uuid)
  <cipher>_<size>b.txt   - UUID strings, one per line (uuid only)
  <cipher>_<size>b.meta.json - builder metadata (keys/iv/original_len...)

Emitted C symbols:  kEncrypted[] (or kUuids[]/kUuidCount for uuid),
                    kEncryptedLen, kOriginalLen
Emitted C# members: Payload.Data (byte[] or string[]), Payload.Count,
                    Payload.OriginalLen
"""
import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PAYLOAD_DIR = ROOT / "payloads"

UUID_TXT_BYTES_PER_LINE = 37  # 36 chars + '\n'


def read_meta(cipher: str, size: int) -> dict:
    meta_path = PAYLOAD_DIR / f"{cipher}_{size}b.meta.json"
    if not meta_path.exists():
        sys.exit(f"[-] missing meta: {meta_path}")
    return json.loads(meta_path.read_text())


def load_blob(cipher: str, size: int) -> bytes:
    """Return the bytes that must be embedded (binary or UUID text)."""
    if cipher == "uuid":
        txt = PAYLOAD_DIR / f"{cipher}_{size}b.txt"
        if not txt.exists():
            sys.exit(f"[-] missing uuid text: {txt}")
        return txt.read_text().strip().encode()
    bin_path = PAYLOAD_DIR / f"{cipher}_{size}b.bin"
    if not bin_path.exists():
        sys.exit(f"[-] missing blob: {bin_path}")
    return bin_path.read_bytes()


def emit_cpp(cipher: str, size: int, meta: dict, out: Path) -> None:
    blob = load_blob(cipher, size)
    lines = [
        "/* payload_inc.h - generated by tools/gen_inc.py (shellcrypt toolkit) */",
        "#pragma once",
        f"/* method={meta.get('method')} encode={meta.get('encode')} "
        f"original_len={meta.get('original_len')} payload_len={meta.get('payload_len')} */",
        f"static const unsigned kOriginalLen = {meta['original_len']};",
    ]
    if cipher == "uuid":
        uuids = blob.decode().splitlines()
        lines.append(f"static const unsigned kUuidCount = {len(uuids)};")
        lines.append("static const char *const kUuids[] = {")
        for u in uuids:
            lines.append(f'    "{u}",')
        lines.append("};")
    else:
        lines.append(f"static const unsigned kEncryptedLen = {len(blob)};")
        lines.append("static const uint8_t kEncrypted[] = {")
        for i in range(0, len(blob), 12):
            chunk = blob[i : i + 12]
            lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
        lines.append("};")
    out.write_text("\n".join(lines) + "\n")
    print(f"[+] wrote {out}")


def emit_cs(cipher: str, size: int, meta: dict, out: Path) -> None:
    blob = load_blob(cipher, size)
    lines = [
        "/* payload_inc.cs - generated by tools/gen_inc.py (shellcrypt toolkit) */",
        "// method=" + str(meta.get("method")) + " encode=" + str(meta.get("encode"))
        + " original_len=" + str(meta.get("original_len"))
        + " payload_len=" + str(meta.get("payload_len")),
        "static class Payload",
        "{",
        f"    public const int OriginalLen = {meta['original_len']};",
    ]
    if cipher == "uuid":
        uuids = blob.decode().splitlines()
        lines.append(f"    public const int Count = {len(uuids)};")
        lines.append("    public static readonly string[] Data = new string[]")
        lines.append("    {")
        for u in uuids:
            lines.append(f'        "{u}",')
        lines.append("    };")
    else:
        lines.append(f"    public const int Len = {len(blob)};")
        lines.append("    public static readonly byte[] Data = new byte[]")
        lines.append("    {")
        for i in range(0, len(blob), 12):
            chunk = blob[i : i + 12]
            lines.append("        " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
        lines.append("    };")
    lines.append("}")
    out.write_text("\n".join(lines) + "\n")
    print(f"[+] wrote {out}")


def main() -> None:
    ap = argparse.ArgumentParser(description="Generate payload_inc for loader templates")
    ap.add_argument("cipher", help="aes_cbc|aes_ctr|xor|rc4|bcrypt|chacha20|uuid")
    ap.add_argument("size", type=int, help="payload size: 4 or 300")
    ap.add_argument("--lang", choices=["cpp", "cs"], default="cpp")
    ap.add_argument("--out", help="output file (default payload_inc.h/.cs next to loader)")
    args = ap.parse_args()

    cipher = args.cipher.lower()
    if cipher not in ("aes_cbc", "aes_ctr", "xor", "rc4", "bcrypt", "chacha20", "uuid"):
        sys.exit(f"[-] unknown cipher: {cipher}")
    if args.size not in (4, 300):
        sys.exit("[-] size must be 4 or 300")

    meta = read_meta(cipher, args.size)
    out = Path(args.out) if args.out else PAYLOAD_DIR / ("payload_inc.h" if args.lang == "cpp" else "payload_inc.cs")
    if args.lang == "cpp":
        emit_cpp(cipher, args.size, meta, out)
    else:
        emit_cs(cipher, args.size, meta, out)


if __name__ == "__main__":
    main()
